/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modal.Sach;
import modal.TheLoai;
import service.SachDao;
import service.theLoaiDao;

/**
 *
 * @author dangd
 */
public class NewJFrame extends javax.swing.JFrame {

    List<TheLoai> listTL;
    List<Sach> listS;
    SachDao sachDao;
    theLoaiDao thLoaiDao;
    int index = 0;
    DefaultTableModel tblModel;

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        setLocationRelativeTo(null);
        TXTMAS.setEnabled(false);
        sachDao = new SachDao();
        thLoaiDao = new theLoaiDao();
        listTL = new ArrayList<>();
        listS = new ArrayList<>();
        tblModel = (DefaultTableModel) TBLSHOW.getModel();
        loadCbo();
    }

    public void loadCbo() {
        CBOTL.removeAllItems();
        listTL = thLoaiDao.getAll();
        for (TheLoai theLoai : listTL) {
            CBOTL.addItem(theLoai.getMaTL());
        }
    }

    public void fillTable(String maTL) {
        tblModel.setRowCount(0);
        listS = sachDao.getAll(maTL);
        for (Sach s : listS) {
            tblModel.addRow(new Object[]{s.getMaS(), s.getTenS(), s.getMaTL(), s.getNxb(), s.getSoL(), s.getGiaT()});
        }
        tblModel.fireTableDataChanged();
    }

    public void mouseClick() {
        index = TBLSHOW.getSelectedRow();
        Sach s = listS.get(index);
        TXTMAS.setText(s.getMaS());
        TXTTENS.setText(s.getTenS());
        CBOTL.setSelectedItem(s.getMaS());
        TXTNXB.setText(s.getNxb());
        TXTSOL.setText(s.getSoL() + "");
        TXTGIAT.setText(s.getGiaT() + "");
    }

    public void update() {
        if (TXTMAS.getText().isEmpty() || TXTTENS.getText().isEmpty() || TXTNXB.getText().isEmpty() || TXTSOL.getText().isEmpty() || TXTGIAT.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Không được để trống!!!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        index = TBLSHOW.getSelectedRow();
        Sach s = listS.get(index);
        s.setMaS(TXTMAS.getText());
        s.setTenS(TXTTENS.getText());
        s.setNxb(TXTNXB.getText());
        s.setSoL(Integer.parseInt(TXTSOL.getText()));
        s.setGiaT(Double.parseDouble(TXTGIAT.getText()));

        sachDao.update(s);
        JOptionPane.showMessageDialog(this, "Sửa thành công !!!");
        return;
    }

    public void delete() {
        index = TBLSHOW.getSelectedRow();
        Sach s = listS.get(index);
        s.setMaS(TXTMAS.getText());
        sachDao.delete(s);
        JOptionPane.showMessageDialog(this, "Sửa thành công !!!");
        return;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TXTMAS = new javax.swing.JTextField();
        TXTTENS = new javax.swing.JTextField();
        TXTNXB = new javax.swing.JTextField();
        TXTSOL = new javax.swing.JTextField();
        TXTGIAT = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        CBOTL = new javax.swing.JComboBox<>();
        LBL = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TBLSHOW = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("MÃ THỂ LOẠI:");

        jLabel2.setText("MÃ SACH:");

        jLabel3.setText("TÊN SÁCH:");

        jLabel4.setText("NXB:");

        jLabel5.setText("SỐ LƯỢNG:");

        jLabel6.setText("GIÁ TIỀN:");

        jButton1.setText("UPDATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("DELETE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        CBOTL.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CBOTL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBOTLActionPerformed(evt);
            }
        });

        LBL.setText("jLabel7");

        TBLSHOW.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MÃ SÁCH", "TÊN SÁCH", "MÃ TL", "NXB", "SỐ LƯỢNG", "GIÁ TIỀN"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TBLSHOW.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBLSHOWMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TBLSHOW);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(CBOTL, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(LBL, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TXTGIAT, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TXTSOL, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TXTMAS, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(TXTNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton2))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(TXTTENS, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(63, 63, 63)
                                    .addComponent(jButton1))))))
                .addContainerGap(83, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CBOTL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LBL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TXTMAS, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TXTTENS, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TXTNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TXTSOL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TXTGIAT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        update();
        fillTable(CBOTL.getSelectedItem() + "");// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        delete();
        fillTable(CBOTL.getSelectedItem() + "");// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void TBLSHOWMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBLSHOWMouseClicked
        mouseClick();        // TODO add your handling code here:
    }//GEN-LAST:event_TBLSHOWMouseClicked

    private void CBOTLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBOTLActionPerformed
        fillTable(CBOTL.getSelectedItem() + "");
        index = CBOTL.getSelectedIndex();
        if (index == -1) {
            return;
        } else {
            TheLoai tl = listTL.get(index);
            LBL.setText(tl.getTenTL());
        }
        if (listS.isEmpty()) {
            return;
        } else {
            TBLSHOW.setRowSelectionInterval(0, 0);
            mouseClick();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_CBOTLActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBOTL;
    private javax.swing.JLabel LBL;
    private javax.swing.JTable TBLSHOW;
    private javax.swing.JTextField TXTGIAT;
    private javax.swing.JTextField TXTMAS;
    private javax.swing.JTextField TXTNXB;
    private javax.swing.JTextField TXTSOL;
    private javax.swing.JTextField TXTTENS;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
