/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modal.KhoaNganh;
import modal.SinhVien;
import service.KhoaNganhDao;
import service.SinhVienDao;

/**
 *
 * @author dangd
 */
public class from2 extends javax.swing.JFrame {

    DefaultTableModel tblModal;
    int index = 0;
    List<SinhVien> listSV;
    List<KhoaNganh> listKN;
    KhoaNganhDao khoaNganhDao;
    SinhVienDao sinhVienDao;

    /**
     * Creates new form from2
     */
    public from2() {
        initComponents();
        listSV = new ArrayList<>();
        listKN = new ArrayList<>();
        khoaNganhDao = new KhoaNganhDao();
        sinhVienDao = new SinhVienDao();
        tblModal = (DefaultTableModel) tblShow.getModel();
        setLocationRelativeTo(null);
        loadCBO();
    }

    public void loadCBO() {
        listKN = khoaNganhDao.getAll();
        CBOKN.removeAllItems();
        for (KhoaNganh khoaNganh : listKN) {
            CBOKN.addItem(khoaNganh.getMaKN());
        }
    }

    public void fillTable(String maKN) {
        tblModal.setRowCount(0);
        listSV = sinhVienDao.getAll(maKN);
        for (SinhVien sinhVien : listSV) {
            tblModal.addRow(new Object[]{sinhVien.getMaSV(), sinhVien.getTenSV(), sinhVien.getSdt(), sinhVien.getEmail()});
        }
        tblModal.fireTableDataChanged();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        CBOKN = new javax.swing.JComboBox<>();
        lblKN = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblShow = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("NEW");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        CBOKN.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CBOKN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBOKNActionPerformed(evt);
            }
        });

        lblKN.setText("jLabel1");

        jLabel1.setText("Mã KN:");

        tblShow.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã SV", "Tên SV", "SDT", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblShow);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(26, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(42, 42, 42)
                        .addComponent(CBOKN, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(lblKN, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(99, 99, 99))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(CBOKN, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKN, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        index = tblShow.getSelectedRow();
        if (index == -1) {
            JOptionPane.showMessageDialog(this, "Vui long chon du lieu!!!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } else if (listSV.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Khong co du lieu!!!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } else {
            String maSV = tblShow.getValueAt(index, 0).toString();
            String ht = tblShow.getValueAt(index, 1).toString();
            String sdt = tblShow.getValueAt(index, 2).toString();
            String email = tblShow.getValueAt(index, 3).toString();
            String maKN = CBOKN.getSelectedItem().toString();
            new from1(maSV, ht, sdt, email, maKN).setVisible(true);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void CBOKNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBOKNActionPerformed
        // TODO add your handling code here:
        index = CBOKN.getSelectedIndex();
        if (index == -1) {
            return;
        } else {
            KhoaNganh kn = listKN.get(index);
            String TenKN = kn.getTenKN();
            lblKN.setText(TenKN);
            fillTable(CBOKN.getSelectedItem() + "");
        }
        if (listSV.isEmpty()) {
            return;
        } else {
            tblShow.setRowSelectionInterval(0, 0);
        }
    }//GEN-LAST:event_CBOKNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(from2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(from2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(from2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(from2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new from2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBOKN;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblKN;
    private javax.swing.JTable tblShow;
    // End of variables declaration//GEN-END:variables
}
