/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import from.*;
import Class.*;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author dangd
 */
public class Main_From extends javax.swing.JFrame {

    // biến toàn cục của 2 JPanelFrom
    private StudenManagmentPanel menuST;
    private GRADEManagmentPanel menuGRADE;

    /**
     * Creates new form Main_From
     */
    public Main_From() {

        initComponents();
        this.setLocationRelativeTo(null);
        // mở from hiển thị full màn hình
        this.setExtendedState(getExtendedState() | JFrame.MAXIMIZED_BOTH);

    }

    // Tabb Student
    public void panelStudent() {
        try {
            if (this.menuST == null) {
                this.menuST = new StudenManagmentPanel();
                ImageIcon icon = new ImageIcon(getClass()
                        .getResource("/image/10207-man-student-light-skin-tone-icon-32.png"));
                this.tplMainBoard.addTab("Quản lý sinh viên", icon, this.menuST, "Quản lý sinh viên");
            }
            this.tplMainBoard.setSelectedComponent(this.menuST);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    // Tabb Grade
    public void panelGradeStudent() {
        try {
            if (this.menuGRADE == null) {
                this.menuGRADE = new GRADEManagmentPanel();
                ImageIcon icon = new ImageIcon(getClass()
                        .getResource("/image/gpa-icon-32.png"));
                this.tplMainBoard.addTab("Quản lý điểm sinh viên", icon, this.menuGRADE, "Quản lý điểm sinh viên");
            }
            this.tplMainBoard.setSelectedComponent(this.menuGRADE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            e.printStackTrace();
        }
    }

    // JDialogFrom About
    public void AboutDialog() {
        AboutDialog ab = new AboutDialog(this, true);
        ab.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnLogout = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        btnQLSV = new javax.swing.JButton();
        btnQLDSV = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        btnAbout = new javax.swing.JButton();
        tplMainBoard = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lblLogin = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        menu_Exit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuStudent = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menuGPA = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuND = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuGT = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        btnLogout.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logout-icon-48.png"))); // NOI18N
        btnLogout.setText("   ĐĂNG XUẤT  ");
        btnLogout.setFocusable(false);
        btnLogout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLogout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jToolBar1.add(btnLogout);
        jToolBar1.add(jSeparator4);

        btnQLSV.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnQLSV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/10207-man-student-light-skin-tone-icon-32.png"))); // NOI18N
        btnQLSV.setText("QUẢN LÝ SINH VIÊN");
        btnQLSV.setFocusable(false);
        btnQLSV.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnQLSV.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnQLSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLSVActionPerformed(evt);
            }
        });
        jToolBar1.add(btnQLSV);

        btnQLDSV.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnQLDSV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/gpa-icon-32.png"))); // NOI18N
        btnQLDSV.setText("QUẢN LÝ ĐIỂM");
        btnQLDSV.setFocusable(false);
        btnQLDSV.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnQLDSV.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnQLDSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLDSVActionPerformed(evt);
            }
        });
        jToolBar1.add(btnQLDSV);
        jToolBar1.add(jSeparator6);

        btnAbout.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Actions-help-about-icon-48.png"))); // NOI18N
        btnAbout.setText("GIỚI THIỆU");
        btnAbout.setFocusable(false);
        btnAbout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAbout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAboutActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAbout);

        lblLogin.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblRole.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblRole.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(96, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addComponent(lblRole, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRole, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );

        jMenu1.setText("Hệ Thống");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logout-icon-16.png"))); // NOI18N
        jMenuItem1.setText("Đăng Xuất");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);
        jMenu1.add(jSeparator3);

        menu_Exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menu_Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Button-Close-icon-16.png"))); // NOI18N
        menu_Exit.setText("Thoát");
        menu_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_ExitActionPerformed(evt);
            }
        });
        jMenu1.add(menu_Exit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Quản Lý");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        menuStudent.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/10207-man-student-light-skin-tone-icon-16.png"))); // NOI18N
        menuStudent.setText("Quản Lý Sinh Viên");
        menuStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuStudentActionPerformed(evt);
            }
        });
        jMenu2.add(menuStudent);
        jMenu2.add(jSeparator2);

        menuGPA.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuGPA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/gpa-icon.png"))); // NOI18N
        menuGPA.setText("Quản Lý Điểm");
        menuGPA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGPAActionPerformed(evt);
            }
        });
        jMenu2.add(menuGPA);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Trợ Giúp");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        menuND.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Actions-help-about-icon-16.png"))); // NOI18N
        menuND.setText("Nội Dung");
        menuND.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNDActionPerformed(evt);
            }
        });
        jMenu3.add(menuND);
        jMenu3.add(jSeparator1);

        menuGT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Help-icon-16.png"))); // NOI18N
        menuGT.setText("Giới Thiệu");
        jMenu3.add(menuGT);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tplMainBoard, javax.swing.GroupLayout.DEFAULT_SIZE, 1021, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 795, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tplMainBoard, javax.swing.GroupLayout.DEFAULT_SIZE, 675, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        this.btnLogoutActionPerformed(evt);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void menuGPAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGPAActionPerformed
        this.panelGradeStudent();
    }//GEN-LAST:event_menuGPAActionPerformed

    private void menu_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_ExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_menu_ExitActionPerformed

    private void menuStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuStudentActionPerformed
        this.panelStudent();
    }//GEN-LAST:event_menuStudentActionPerformed

    private void btnQLSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLSVActionPerformed
        // TODO add your handling code here:
        this.panelStudent();
    }//GEN-LAST:event_btnQLSVActionPerformed

    private void btnQLDSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLDSVActionPerformed
        // TODO add your handling code here:
        this.panelGradeStudent();
    }//GEN-LAST:event_btnQLDSVActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
        this.panelGradeStudent();
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void btnAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAboutActionPerformed
        // TODO add your handling code here:
        this.AboutDialog();
    }//GEN-LAST:event_btnAboutActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:
        this.AboutDialog();
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        this.logOut();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void menuNDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNDActionPerformed
        // TODO add your handling code here:
        NoiDungDialog nd = new NoiDungDialog(this, true);
        nd.setVisible(true);
    }//GEN-LAST:event_menuNDActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
//        this.logOut();
    }//GEN-LAST:event_formWindowOpened
    public void logOut() {
        LoginDialog logout = new LoginDialog(this, true);
        logout.setVisible(true);
        this.processLogin();
    }
    // lấy thông tin từ người đăng nhập
    private void processLogin() {
        this.lblLogin.setText(ShearchData.nguoiDangNhap.getUsername());
        this.lblRole.setText(ShearchData.nguoiDangNhap.getRole());
        this.tplMainBoard.removeAll();
        if (ShearchData.nguoiDangNhap.getRole().equals("Giáo viên")) {
            this.menuStudent.setEnabled(true);
            this.menuGPA.setEnabled(false);
            this.btnQLSV.setEnabled(true);
            this.btnQLDSV.setEnabled(false);
        } else if (ShearchData.nguoiDangNhap.getRole().equals("Đào tạo")) {
            this.menuStudent.setEnabled(false);
            this.menuGPA.setEnabled(true);
            this.btnQLSV.setEnabled(false);
            this.btnQLDSV.setEnabled(true);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_From.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_From.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_From.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_From.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new Main_From().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbout;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnQLDSV;
    private javax.swing.JButton btnQLSV;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblRole;
    private javax.swing.JMenuItem menuGPA;
    private javax.swing.JMenuItem menuGT;
    private javax.swing.JMenuItem menuND;
    private javax.swing.JMenuItem menuStudent;
    private javax.swing.JMenuItem menu_Exit;
    private javax.swing.JTabbedPane tplMainBoard;
    // End of variables declaration//GEN-END:variables
}
