/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import modal.SinhVien;
import modal.khoaNganh;
import service.SinhVienDao;
import service.khoaNganhDao;

/**
 *
 * @author dangd
 */
public class from2 extends javax.swing.JFrame {

    List<SinhVien> listSV;
    List<khoaNganh> listKN;
    khoaNganhDao khNganhDao;
    SinhVienDao sinhVienDao;
    DefaultTableModel tblModal;
    int index = 0;

    /**
     * Creates new form from2
     */
    public from2() {
        initComponents();
        setLocationRelativeTo(null);
        listKN = new ArrayList<>();
        listSV = new ArrayList<>();
        khNganhDao = new khoaNganhDao();
        sinhVienDao = new SinhVienDao();
        tblModal = (DefaultTableModel) tblShow.getModel();
        loadCBO();
    }

    public void loadCBO() {
        try {
            cboKN.removeAllItems();
            listKN = khNganhDao.getAll();
            for (khoaNganh nganh : listKN) {
                cboKN.addItem(nganh.getMaKN());
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void fillTable(String maKN) {
        try {
            tblModal.setRowCount(0);
            listSV = sinhVienDao.getAll(maKN);
            for (SinhVien sinhVien : listSV) {
                tblModal.addRow(new Object[]{sinhVien.getMaSV(), sinhVien.getTenSV(), sinhVien.getSDT(), sinhVien.getEmail()});
            }
//            tblModal.fireTableDataChanged();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblShow = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        cboKN = new javax.swing.JComboBox<>();
        lbl = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblShow.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã SV", "Họ tên", "SDT", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblShow);

        jLabel1.setText("Mã KN:");

        cboKN.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboKN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboKNActionPerformed(evt);
            }
        });

        lbl.setText("jLabel2");

        jButton1.setText("NEW");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(cboKN, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboKN, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboKNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboKNActionPerformed
        // TODO add your handling code here:
        index = cboKN.getSelectedIndex();
        if (index == -1) {
            return;
        } else {
            khoaNganh kn = listKN.get(index);
            String tenKN = kn.getTenKN();
            lbl.setText(tenKN);
            fillTable(cboKN.getSelectedItem() + "");
        }
        if (listSV.isEmpty()) {
            return;
        } else {
            index  = 0;
            tblShow.setRowSelectionInterval(index, index);
        }


    }//GEN-LAST:event_cboKNActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        index = tblShow.getSelectedRow();
        if (listSV.isEmpty()) {
            JOptionPane.showMessageDialog(this, "ko co du lieu!!!!");
            return;
        } else if (index == -1) {
            JOptionPane.showMessageDialog(this, "vui long chon!!!!");
            return;
        } else {
            String masv = tblShow.getValueAt(index, 0).toString();
            String ht = tblShow.getValueAt(index, 1).toString();
            String sdt = tblShow.getValueAt(index, 2).toString();
            String email = tblShow.getValueAt(index, 3).toString();
            String maKn = cboKN.getSelectedItem() + "";
            new from1(masv, ht, sdt, email, maKn).setVisible(true);
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(from2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(from2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(from2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(from2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new from2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboKN;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl;
    private javax.swing.JTable tblShow;
    // End of variables declaration//GEN-END:variables
}
